### ISSUE TITLE
metric_CPU utilization (%) > 100

### ISSUE THREAD

**Issue by jasonneverstop** [intel/PerfSpect#8]
When I use 'perfspect -p' to target only one process,the metric_CPU utilization is greater than 100.I want to know why and how to solve it.

**Comment by hilldani** [comment]
Thanks for bringing this up. Some hardware events dont translate perfectly to the pid mode of perf. I will look into whether this is the case or not for cpu utilization and get back to you / update pid mode

**Comment by ashrafMahgoub** [comment]
@jasonneverstop Thank you for reporting this issue. The metric CPU utilization uses **reference cycles** to identify the utilization % for a given pid. Since **reference cycles** does not account for dynamic changes to the clock frequency, the value can sometimes exceed 100% with the current implementation. We will add a fix for this issue in the next release.

**Comment by ashrafMahgoub** [comment]
@jasonneverstop We now released V1.2.3 with a the fix for this issue: https://github.com/intel/PerfSpect/releases/tag/1.2.3. Please try it out and let us know your feedback.
